# Generated by Django 4.2 on 2023-05-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnatoApp', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
