# Generated by Django 4.2 on 2023-05-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnatoApp', '0007_alter_entrada_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='imagen',
        ),
    ]
