# Generated by Django 4.2 on 2023-05-20 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnatoApp', '0008_remove_entrada_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
