# Generated by Django 4.0.7 on 2023-05-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('picture', models.BinaryField(editable=True)),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Gato',
        ),
        migrations.DeleteModel(
            name='Pajaro',
        ),
        migrations.DeleteModel(
            name='Perro',
        ),
    ]
