# Generated by Django 4.0.7 on 2023-05-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_delete_gato_delete_pajaro_delete_perro'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_type',
            field=models.CharField(help_text='Tipo de Archivo', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
