# Generated by Django 4.0.7 on 2023-05-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog_content_type_alter_blog_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(default=None, upload_to='imagenes/'),
            preserve_default=False,
        ),
    ]
