# Generated by Django 4.0.7 on 2023-05-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_blog_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_type',
            field=models.CharField(help_text='Aca guardamos el archivo', max_length=256, null=True),
        ),
    ]
