# Generated by Django 4.2 on 2023-05-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('renta', models.IntegerField()),
                ('alimentacion', models.IntegerField()),
                ('educacion', models.IntegerField()),
                ('transporte', models.IntegerField()),
                ('bills', models.IntegerField()),
                ('vestuario', models.IntegerField()),
                ('recreacion', models.IntegerField()),
                ('otros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('salario', models.IntegerField()),
                ('part_time', models.IntegerField()),
                ('alquileres', models.IntegerField()),
                ('otros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cryptocurrency', models.IntegerField()),
                ('acciones', models.IntegerField()),
                ('otros', models.IntegerField()),
            ],
        ),
    ]
