# Generated by Django 4.2 on 2023-05-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='comentario',
            field=models.CharField(max_length=140),
        ),
    ]
