# Generated by Django 4.2 on 2023-05-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_calificacion_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acerca', models.CharField(max_length=140)),
            ],
        ),
    ]
