# Generated by Django 4.2 on 2023-05-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('consulta', models.CharField(max_length=140)),
            ],
        ),
    ]
