# Generated by Django 4.2 on 2023-04-28 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetas',
            name='author',
        ),
    ]
