# Generated by Django 4.2 on 2023-05-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0003_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recetas',
            old_name='decripcion',
            new_name='descripcion',
        ),
    ]
