# Generated by Django 4.2 on 2023-05-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='imagen',
            field=models.ImageField(null=True, upload_to='vendedores'),
        ),
    ]
