# Generated by Django 4.2 on 2023-05-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_alter_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='valor_predeterminado'),
        ),
    ]
