# Generated by Django 4.2 on 2023-05-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=100)),
                ('opinion', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='opinion',
            old_name='opinion',
            new_name='mensaje',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.AddField(
            model_name='opinion',
            name='debate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='App1.debate'),
            preserve_default=False,
        ),
    ]
