# Generated by Django 4.2 on 2023-05-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTennis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='torneo',
        ),
        migrations.AddField(
            model_name='jugador',
            name='comentario',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jugador',
            name='dni',
            field=models.CharField(default='none', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='email',
            field=models.EmailField(default='', max_length=144),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='telefono',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='comentario',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
