# Generated by Django 4.2.1 on 2023-05-12 17:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_posts_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="Message",
            field=ckeditor.fields.RichTextField(default=""),
        ),
    ]
