# Generated by Django 4.2.1 on 2023-05-13 00:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_posts_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posts",
            options={"ordering": ["-dateAdded"]},
        ),
    ]
