# Generated by Django 4.2.1 on 2023-05-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_posts_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="dateModified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
