# Generated by Django 4.2.1 on 2023-05-14 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_posts_datemodified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posts",
            options={
                "ordering": ["-dateModified"],
                "permissions": (
                    ("can_view", "Can view Posts"),
                    ("can_edit", "Can edit Posts"),
                    ("can_delete", "Can delete Posts"),
                ),
            },
        ),
    ]
