# Generated by Django 4.2.1 on 2023-05-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_posts_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="subtitle",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="posts",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
