# Generated by Django 3.2.18 on 2023-04-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20201007_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Foto_perfil_Generica.png', upload_to=''),
        ),
    ]
