# Generated by Django 3.2.7 on 2021-10-10 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuo',
            name='aprobado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='individuo',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individuos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individuo',
            name='fecha_nacimineto',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='individuo',
            name='visitas',
            field=models.IntegerField(null=True),
        ),
    ]
