# Generated by Django 3.2.7 on 2021-10-10 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20211010_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_ingreso', models.DateField(null=True)),
                ('Fecha_salida', models.DateField(null=True)),
                ('aprobado', models.BooleanField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='individuo',
            name='fecha_nacimineto',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(null=True)),
                ('abierto', models.BooleanField()),
                ('entidad', models.CharField(max_length=200)),
                ('monto', models.IntegerField(null=True)),
                ('comentarios', models.TextField(null=True)),
                ('aprobado', models.BooleanField(null=True)),
                ('visitas', models.IntegerField(null=True)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('visitas', models.IntegerField(null=True)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Implicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afiliado_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implicados', to='app.afiliacion')),
                ('proceso_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='implicados', to='app.proceso')),
            ],
        ),
        migrations.AddField(
            model_name='afiliacion',
            name='individuo_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='afiliaciones', to='app.individuo'),
        ),
        migrations.AddField(
            model_name='afiliacion',
            name='partido_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='afiliaciones', to='app.partido'),
        ),
    ]
