# Generated by Django 3.2.7 on 2021-10-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211010_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='implicado',
            name='acusacion',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implicado',
            name='comentarios',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='implicado',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='implicado',
            name='pena',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
