# Generated by Django 4.2.1 on 2023-05-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='contenido',
            field=models.TextField(max_length=400),
        ),
    ]
