# Generated by Django 4.2 on 2023-05-20 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensajes', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajeria',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='mensajeria',
            name='enviarA',
        ),
        migrations.AddField(
            model_name='mensajeria',
            name='destinatario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensajeria',
            name='remitente',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
