# Generated by Django 4.1.7 on 2023-04-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tienda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodcto",
            name="imagen",
            field=models.ImageField(null=True, upload_to="productos"),
        ),
    ]
