# Generated by Django 4.1.7 on 2023-04-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tienda", "0002_prodcto_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("correo", models.EmailField(max_length=254)),
                (
                    "tipo_consulta",
                    models.IntegerField(
                        choices=[
                            [0, "consulta"],
                            [1, "reclamo"],
                            [2, "sugerencia"],
                            [3, "felicitaciones"],
                        ]
                    ),
                ),
                ("mensaje", models.TextField()),
                ("avisos", models.BooleanField()),
            ],
        ),
    ]
