# Generated by Django 4.2 on 2023-05-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_categoria_options_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('nombre',)},
        ),
    ]
