# Generated by Django 4.2 on 2023-05-20 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagenPortada',
        ),
        migrations.CreateModel(
            name='PostImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
