# Generated by Django 4.2.1 on 2023-05-17 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "mensajeria",
            "0005_chatroom_alter_message_options_remove_message_chat_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MessagesChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="name",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="messages",
            field=models.ManyToManyField(to="mensajeria.messageschat"),
        ),
    ]
