# Generated by Django 4.2.1 on 2023-05-18 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "mensajeria",
            "0006_messageschat_remove_chatroom_name_delete_message_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageschat",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="messageschat",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
