# Generated by Django 4.2.1 on 2023-05-20 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mensajeria", "0007_alter_messageschat_receiver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageschat",
            name="sender",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
    ]
