# Generated by Django 4.2 on 2023-04-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='Costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='curso',
            name='Jornada',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='Tipo',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Telefono',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profesor',
            name='Documento',
            field=models.IntegerField(default=0),
        ),
    ]
