# Generated by Django 4.2 on 2023-04-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_curso_costo_curso_jornada_curso_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='Costo',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='curso',
            name='Jornada',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='Tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='Documento',
            field=models.IntegerField(),
        ),
    ]
