# Generated by Django 4.2 on 2023-04-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_cursos_profesor_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='Documento',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profesor',
            name='Documento',
            field=models.IntegerField(default=0.0),
        ),
    ]
