# Generated by Django 4.2 on 2023-05-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_entregable_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='curso',
            field=models.ManyToManyField(blank=True, to='app.curso'),
        ),
    ]
