# Generated by Django 4.2.1 on 2023-05-10 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_curso_estudiante_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='curso',
        ),
        migrations.AddField(
            model_name='profesor',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
            preserve_default=False,
        ),
    ]
