# Generated by Django 4.2.1 on 2023-05-18 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_profesor_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='Curso',
            new_name='curso',
        ),
        migrations.AlterField(
            model_name='profesor',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
    ]
