# Generated by Django 4.2 on 2023-05-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_thread_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
