# Generated by Django 4.2 on 2023-05-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_remove_thread_created_by_delete_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opinion',
        ),
    ]
