# Generated by Django 4.1.7 on 2023-05-03 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carrito", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Producto",
        ),
    ]
