# Generated by Django 4.2 on 2023-04-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdBuzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tamaño', models.CharField(max_length=3)),
                ('color', models.CharField(max_length=10)),
                ('precio', models.FloatField()),
                ('disp', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProdPantalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tamaño', models.CharField(max_length=3)),
                ('color', models.CharField(max_length=10)),
                ('diseño', models.CharField(choices=[('CA', 'Cargo'), ('EL', 'Elastizado'), ('MO', 'Mom'), ('WL', 'Wideleg')], default='CA', max_length=20)),
                ('precio', models.FloatField()),
                ('disp', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProdRemera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tamaño', models.CharField(max_length=3)),
                ('color', models.CharField(max_length=10)),
                ('precio', models.FloatField()),
                ('disp', models.BooleanField()),
            ],
        ),
    ]
