# Generated by Django 4.2 on 2023-04-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPreEntreg3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodbuzo',
            name='disp',
        ),
        migrations.RemoveField(
            model_name='prodpantalon',
            name='disp',
        ),
        migrations.RemoveField(
            model_name='prodremera',
            name='disp',
        ),
        migrations.AddField(
            model_name='prodbuzo',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodpantalon',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodremera',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
