# Generated by Django 4.2.1 on 2023-05-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
