# Generated by Django 4.2.1 on 2023-05-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_first_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="first_name",
            new_name="last_name",
        ),
        migrations.AddField(
            model_name="profile",
            name="nombre",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
