# Generated by Django 4.2.1 on 2023-05-08 01:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_first_name_profile_last_name_profile_nombre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="nombre",
            new_name="first_name",
        ),
    ]
