# Generated by Django 4.2.1 on 2023-05-08 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_rename_nombre_profile_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
    ]
