# Generated by Django 4.2 on 2023-05-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_vista', '0002_astronomía_biología_filosofía_medicina_tecnología_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembros',
            name='email',
        ),
        migrations.AddField(
            model_name='miembros',
            name='universidad',
            field=models.CharField(default='Universidad', max_length=50),
        ),
    ]
