# Generated by Django 4.2 on 2023-05-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_vista', '0003_remove_miembros_email_miembros_universidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembros',
            name='universidad',
        ),
    ]
