# Generated by Django 4.2 on 2023-05-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_vista', '0004_remove_miembros_universidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembros',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='miembros',
            name='universidad',
            field=models.CharField(default='Sin universidad', max_length=50),
        ),
        migrations.AlterField(
            model_name='miembros',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
