# Generated by Django 4.2 on 2023-05-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_vista', '0006_alter_astronomía_imagen_alter_biología_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembros',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='miembros',
            name='universidad',
            field=models.CharField(max_length=30),
        ),
    ]
