# Generated by Django 4.2 on 2023-04-30 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("correo", models.EmailField(max_length=254)),
                (
                    "tipo_consulta",
                    models.IntegerField(
                        choices=[
                            [0, "consulta"],
                            [1, "reclamo"],
                            [2, "sugerencia"],
                            [3, "felicitaciones"],
                        ]
                    ),
                ),
                ("mensaje", models.TextField()),
                ("avisos", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("precio", models.IntegerField()),
                ("descripcion", models.TextField()),
                ("nuevo", models.BooleanField()),
                ("fecha_fabricacion", models.DateField()),
                ("imagen", models.ImageField(null=True, upload_to="productos")),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tiendaApp.category",
                    ),
                ),
            ],
        ),
    ]
