# Generated by Django 4.2 on 2023-04-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiendaApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="fecha_fabricacion",
            field=models.DateField(auto_now=True),
        ),
    ]
