# Generated by Django 4.2 on 2023-04-30 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tiendaApp", "0002_alter_products_fecha_fabricacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="marca",
        ),
        migrations.AddField(
            model_name="products",
            name="categoria",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="tiendaApp.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="products",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
