# Generated by Django 4.2 on 2023-05-01 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tiendaApp", "0003_remove_products_marca_products_categoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias_prod",
                to="tiendaApp.category",
            ),
        ),
    ]
