# Generated by Django 4.2 on 2023-05-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiendaApp", "0004_alter_products_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
