# Generated by Django 4.2 on 2023-05-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='products/', verbose_name='Imagen'),
        ),
    ]
