# Generated by Django 4.2 on 2023-05-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('precioTotal', models.IntegerField()),
            ],
        ),
    ]
