# Generated by Django 3.2.19 on 2023-05-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_comprausuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprausuario',
            name='precioTotal',
        ),
    ]
